version: "3.8"
services:
  nifi:
    container_name: nifi
    image: apache/nifi:1.13.2
    ports:
      - 12010:8800
      - 12021:9092
    environment:
      - NIFI_WEB_HTTP_PORT=8800
    volumes:
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_logs:/opt/nifi/nifi-current/logs
      - nifi_data:/opt/nifi/nifi-current/data
    networks:
      - nifi

volumes:
  nifi_content_repository:
    driver: local
  nifi_database_repository:
    driver: local
  nifi_flowfile_repository:
    driver: local
  nifi_provenance_repository:
    driver: local
  nifi_conf:
    driver: local
  nifi_state:
    driver: local
  nifi_logs:
    driver: local
  nifi_data:
    driver: local
      
networks:
  nifi:
    driver: bridge