version: '3'

services:
  cassandra:
    image: cassandra:4.0
    hostname: cassandra
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra
    volumes:
      - ./data:/var/lib/cassandra

networks:
  default:
    external:
      name: kafka-cc-spark_kafka